# Generated by Django 5.0.2 on 2024-02-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofinterestrating',
            name='index',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='external_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AddIndex(
            model_name='pointofinterestrating',
            index=models.Index(fields=['point_of_interest'], name='assignment__point_o_ad8869_idx'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_of_interest', to='assignment.pointofinterestcategory'),
        ),
        migrations.DeleteModel(
            name='PointOfInterestCoordinates',
        ),
    ]
